# Generated by Django 4.0.3 on 2022-04-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
