# Generated by Django 4.0.3 on 2022-04-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Work', 'Work'), ('School', 'School')], max_length=10),
        ),
    ]
